language: objective-c
osx_image: xcode8.2
env:
- LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8

script: 
- xcodebuild clean build -workspace Workspace.xcworkspace -scheme Revolver
- xcodebuild test -workspace Workspace.xcworkspace -scheme Revolver

