language: objective-c
osx_image: xcode8.2
env:
- LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8

before_install: 
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script: 
- xctool clean build -workspace Workspace.xcworkspace -scheme Revolver
- xctool test -workspace Workspace.xcworkspace -scheme Revolver

