import SwiftyJSON

/**
 *  Persistent type can be saved to and restored from JSON.
 */
public protocol PersistentType {
    
    /**
     Generate a new instance of the type from JSON.
     
     - parameter json: JSON previously generated by the `toJSON()` method.
     
     - returns: New instance with values loaded from the JSON.
     */
    init(json: JSON)
    
    /**
     Serialize the values of this instance into JSON.
     
     - returns: JSON containing values and state of this object.
     */
    func toJSON() -> JSON
    
}
